[package]
name = "rust_os"
version = "0.1.0"
authors = ["Pratik Rajesh Sampat <pratik.r.sampat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
